# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Words
tagline:             'Thinking about meaning'
description:         'Made by <a href="https://twitter.com/rosszb" target="_blank">@rosszb</a>.'
url:                 https://rossbernet.github.io/
baseurl:             ''
paginate:            5

github:
  repo:              https://github.com/rossbernet/rossblog



# About/contact
author:
  name:              Ross Bernet
  url:               https://twitter.com/rosszb
  email:             rossbernet@gmail.com

# Custom vars
version:             1.0.0
